{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)","children":[{"name":"test_404","uid":"e51a9acebb1231bf","parentUid":"464b4dae86fb5c88f46867622c105366","status":"broken","time":{"start":1706619246547,"stop":1706619246547,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"464b4dae86fb5c88f46867622c105366"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}