{"uid":"524960f29b514b81","name":"test_404","fullName":"tests.category.test_category.TestCategory#test_404","historyId":"41ffa436efe79139330bc24acb3e04ed","time":{"start":1706629295152,"stop":1706629295152,"duration":0},"status":"broken","statusMessage":"sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)","statusTrace":"@pytest.fixture(scope=\"session\", autouse=True)\n    def create_test_database():\n>       if database_exists(url):\n\ntests/confest.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy_utils/functions/database.py:488: in database_exists\n    return bool(_get_scalar_result(engine, sa.text(text)))\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy_utils/functions/database.py:442: in _get_scalar_result\n    with engine.connect() as conn:\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py:3315: in connect\n    return self._connection_cls(self, close_with_result=close_with_result)\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py:96: in __init__\n    else engine.raw_connection()\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py:3394: in raw_connection\n    return self._wrap_pool_connect(self.pool.connect, _connection)\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py:3361: in _wrap_pool_connect\n    return fn()\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py:320: in connect\n    return _ConnectionFairy._checkout(self)\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py:884: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py:486: in checkout\n    rec = pool._do_get()\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/impl.py:145: in _do_get\n    with util.safe_reraise():\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py:70: in __exit__\n    compat.raise_(\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/util/compat.py:208: in raise_\n    raise exception\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/impl.py:143: in _do_get\n    return self._create_connection()\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py:266: in _create_connection\n    return _ConnectionRecord(self)\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py:381: in __init__\n    self.__connect()\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py:677: in __connect\n    with util.safe_reraise():\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py:70: in __exit__\n    compat.raise_(\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/util/compat.py:208: in raise_\n    raise exception\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py:673: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/engine/create.py:578: in connect\n    return dialect.connect(*cargs, **cparams)\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/engine/default.py:598: in connect\n    return self.dbapi.connect(*cargs, **cparams)\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:780: in connect\n    await_only(self.asyncpg.connect(*arg, **kw)),\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nawaitable = <coroutine object connect at 0x7f7c78ca48e0>\n\n    def await_only(awaitable: Coroutine) -> Any:\n        \"\"\"Awaits an async function in a sync method.\n    \n        The sync method must be inside a :func:`greenlet_spawn` context.\n        :func:`await_only` calls cannot be nested.\n    \n        :param awaitable: The coroutine to call.\n    \n        \"\"\"\n        # this is called in the context greenlet while running fn\n        current = greenlet.getcurrent()\n        if not isinstance(current, _AsyncIoGreenlet):\n>           raise exc.MissingGreenlet(\n                \"greenlet_spawn has not been called; can't call await_only() \"\n                \"here. Was IO attempted in an unexpected place?\"\n            )\nE           sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)\n\n/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:59: MissingGreenlet","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1706629295154,"stop":1706629295376,"duration":222},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"create_test_database","time":{"start":1706629295377,"stop":1706629295379,"duration":2},"status":"broken","statusMessage":"sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Myosotis-backend/Myosotis-backend/tests/confest.py\", line 37, in create_test_database\n    if database_exists(url):\n       ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy_utils/functions/database.py\", line 488, in database_exists\n    return bool(_get_scalar_result(engine, sa.text(text)))\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy_utils/functions/database.py\", line 442, in _get_scalar_result\n    with engine.connect() as conn:\n         ^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3315, in connect\n    return self._connection_cls(self, close_with_result=close_with_result)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 96, in __init__\n    else engine.raw_connection()\n         ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3394, in raw_connection\n    return self._wrap_pool_connect(self.pool.connect, _connection)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3361, in _wrap_pool_connect\n    return fn()\n           ^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 320, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 884, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 486, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 145, in _do_get\n    with util.safe_reraise():\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 70, in __exit__\n    compat.raise_(\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/util/compat.py\", line 208, in raise_\n    raise exception\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 143, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 266, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 381, in __init__\n    self.__connect()\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 677, in __connect\n    with util.safe_reraise():\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 70, in __exit__\n    compat.raise_(\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/util/compat.py\", line 208, in raise_\n    raise exception\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 673, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/engine/create.py\", line 578, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 598, in connect\n    return self.dbapi.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 780, in connect\n    await_only(self.asyncpg.connect(*arg, **kw)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 59, in await_only\n    raise exc.MissingGreenlet(\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"parentSuite","value":"tests.category"},{"name":"suite","value":"test_category"},{"name":"subSuite","value":"TestCategory"},{"name":"host","value":"fv-az167-395"},{"name":"thread","value":"2894-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.category.test_category"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"524960f29b514b81.json","parameterValues":[]}